GarageConfig = {
    MC = {
        label = "Motorcycle Club",
        vehicles = {
           {model = "avarus", label = "Avarus", price = 85000},
           {model = "chimera", label = "Chimera", price = 65000},
           {model = "cliffhanger", label = "Cliffhanger", price = 95000},
           {model = "daemon", label = "Daemon", price = 80000},
           {model = "daemon2", label = "Daemon 2", price = 90000},
           {model = "gargoyle", label = "Gargoyle", price = 75000},
           {model = "hexer", label = "Hexer", price = 70000},
           {model = "innovation", label = "Innovation", price = 80000},
           {model = "nightblade", label = "Nightblade", price = 75000},
           {model = "ratbike", label = "Ratbike", price = 45000},
           {model = "rrocket", label = "Rocket", price = 105000},
           {model = "jogger", label = "Jogger", price = 50000},
           {model = "kamacho", label = "Kamacho", price = 105000},
           {model = "sanctus", label = "Sanctus", price = 110000},
           {model = "sovereign", label = "Sovereign", price = 105000},
           {model = "wolfsbane", label = "Wolfsbane", price = 85000},
           {model = "zombiea", label = "Zombie A", price = 105000},
           {model = "zombieb", label = "Zombie B", price = 110000},

        }
    },
    Mafia = {
        label = "Mafia", -- meme véhicule que orga
        vehicles = {
            {model = "argento", label = "Argento", price = 90000},
            {model = "asteropers", label = "Asteropers", price = 105000},
            {model = "ccadeesv", label = "Ccadee SV", price = 150000},
            {model = "ccadefxt", label = "Ccade FXT", price = 105000},
            {model = "buffalo4h", label = "Buffalo 4", price = 95000},
            {model = "draftGPR", label = "Draft GPR", price = 65000},
            {model = "dubsta22", label = "Dubsta 22", price = 95000},
            {model = "hellion", label = "Hellion", price = 100000},
            {model = "elegy4", label = "Elegy 4", price = 75000},
            {model = "elegy", label = "Elegy", price = 70000},
            {model = "everonb", label = "Everon B", price = 60000},
            {model = "hellenstorm", label = "Hellenstorm", price = 120000},
            {model = "howitzer", label = "Howitzer", price = 80000},
            {model = "jogger", label = "Jogger", price = 50000},
            {model = "komodafr", label = "Komoda FR", price = 95000},
            {model = "sunrise1", label = "Sunrise", price = 105000},
            {model = "mesaxl", label = "Mesa XL", price = 100000},
            {model = "scheisser", label = "Scheisser", price = 95000},
            {model = "oraclelwb", label = "Oracle LWB", price = 75000},
            {model = "kuruma", label = "Kuruma", price = 75000},
            {model = "baller4", label = "Baller 4", price = 95000},
            {model = "schafter3rs", label = "Schafter 3RS", price = 90000},
            {model = "aleutianxl", label = "Aleutian XL", price = 150000},
            {model = "scout", label = "Scout", price = 110000},
            {model = "jugular", label = "Jugular", price = 95000},
            {model = "revolter", label = "Revolter", price = 90000},
            {model = "bf400", label = "BF400", price = 65000},
            {model = "cliffhanger", label = "Cliffhanger", price = 95000},
            {model = "enduro", label = "Enduro", price = 45000},
            {model = "manchez", label = "Manchez", price = 55000},
            {model = "manchez2", label = "Manchez 2", price = 65000},
        }
    },
    Gang = {
        label = "Street Gang",
        vehicles = {
           {model = "arias", label = "Arias", price = 35000},
           {model = "cararv", label = "Cararv", price = 75000},
           {model = "buffalo4h", label = "Buffalo 4", price = 95000},
           {model = "elegy4", label = "Elegy 4", price = 75000},
           {model = "elegy", label = "Elegy", price = 70000},
           {model = "everonb", label = "Everon B", price = 60000},
           {model = "gauntletstx", label = "Gauntlet STX", price = 65000},
           {model = "gauntletc", label = "Gauntlet C", price = 70000},
           {model = "gauntletctx", label = "Gauntlet CTX", price = 75000},
           {model = "gresleyh", label = "Gresleyh", price = 85000},
           {model = "gstghell1", label = "Gstghell", price = 95000},
           {model = "jogger", label = "Jogger", price = 50000},
           {model = "sunrise1", label = "Sunrise", price = 85000},
           {model = "remustwo", label = "Remus Two", price = 55000},
           {model = "scheisser", label = "Scheisser", price = 75000},
           {model = "spritzer", label = "Spritzer", price = 105000},
           {model = "jd_oraclev12", label = "Oracle V12", price = 75000},
           {model = "ariant", label = "Ariant", price = 65000},
           {model = "kuruma", label = "Kuruma", price = 75000},
           {model = "vamos", label = "Vamos", price = 55000},
           {model = "sultan2", label = "Sultan 2", price = 95000},
           {model = "sultan3", label = "Sultan 3", price = 105000},
           {model = "futo", label = "Futo", price = 75000},
           {model = "oracle", label = "Oracle", price = 80000},
           {model = "caracara2", label = "Caracara", price = 100000},
           {model = "scharmann", label = "Scharmann", price = 105000},
           {model = "jugular", label = "Jugular", price = 95000},
           {model = "moonbeam2", label = "Moonbeam", price = 45000},
           {model = "bf400", label = "BF400", price = 65000},
           {model = "enduro", label = "Enduro", price = 45000},
           {model = "manchez", label = "Manchez", price = 55000},
           {model = "kamacho", label = "Kamacho", price = 105000},
        },
    },
    Orga = {
        label = "Organization",
        vehicles = {
            {model = "argento", label = "Argento", price = 90000},
            {model = "asteropers", label = "Asteropers", price = 105000},
            {model = "ccadeesv", label = "Ccadee SV", price = 150000},
            {model = "ccadefxt", label = "Ccade FXT", price = 105000},
            {model = "buffalo4h", label = "Buffalo 4", price = 95000},
            {model = "draftGPR", label = "Draft GPR", price = 65000},
            {model = "dubsta22", label = "Dubsta 22", price = 95000},
            {model = "hellion", label = "Hellion", price = 100000},
            {model = "elegy4", label = "Elegy 4", price = 75000},
            {model = "elegy", label = "Elegy", price = 70000},
            {model = "everonb", label = "Everon B", price = 60000},
            {model = "hellenstorm", label = "Hellenstorm", price = 120000},
            {model = "howitzer", label = "Howitzer", price = 80000},
            {model = "jogger", label = "Jogger", price = 50000},
            {model = "komodafr", label = "Komoda FR", price = 95000},
            {model = "sunrise1", label = "Sunrise", price = 105000},
            {model = "mesaxl", label = "Mesa XL", price = 100000},
            {model = "scheisser", label = "Scheisser", price = 95000},
            {model = "oraclelwb", label = "Oracle LWB", price = 75000},
            {model = "kuruma", label = "Kuruma", price = 75000},
            {model = "baller4", label = "Baller 4", price = 95000},
            {model = "schafter3rs", label = "Schafter 3RS", price = 90000},
            {model = "aleutianxl", label = "Aleutian XL", price = 150000},
            {model = "scout", label = "Scout", price = 110000},
            {model = "jugular", label = "Jugular", price = 95000},
            {model = "revolter", label = "Revolter", price = 90000},
            {model = "bf400", label = "BF400", price = 65000},
            {model = "cliffhanger", label = "Cliffhanger", price = 95000},
            {model = "enduro", label = "Enduro", price = 45000},
            {model = "manchez", label = "Manchez", price = 55000},
            {model = "manchez2", label = "Manchez 2", price = 65000},
        }
    }
} 