--Streetnames/area names script

Citizen.CreateThread(function()
    --[[ Streets ]]--
    AddTextEntry("roxsquid", "Squidrillo Fwy")
    AddTextEntry("roxclam", "Clam Way")
    AddTextEntry("roxorteg", "Ortega Dr")
    AddTextEntry("roxparto", "Del Parto Canal St")
    AddTextEntry("roxrivav", "Riverfront Ave")
    AddTextEntry("roxdolph", "Dolphin Dr")
    AddTextEntry("roxsunln", "Sunrise Ln")
    AddTextEntry("roxpearl", "Pearl Rd")
    AddTextEntry("roxconny", "Conny Ln")
    AddTextEntry("roxshell", "Shell Bead Rd")
    AddTextEntry("roxbaydr", "Bayview Dr")
    AddTextEntry("roxvoya", "Great Voyage Rd")
    AddTextEntry("roxbaybr", "Bayview Bridge")
    AddTextEntry("roxdulst", "Dulcis St")
    AddTextEntry("roxfugst", "Fugero St")
    AddTextEntry("roxminvrd", "Minerva Rd")      
    AddTextEntry("roxjunpone", "1st St")     
    AddTextEntry("roxmjunptwo", "2nd St")     
    AddTextEntry("roxjunpthr", "3rd St")
    AddTextEntry("roxjunpthr", "4th St")     
    AddTextEntry("roxr849", "Route 849")     
    AddTextEntry("roxr870", "Route 870")     
    AddTextEntry("roxinters8", "Interstate 8")   
    AddTextEntry("roxsolvbou", "Solverde Boulevard")
    AddTextEntry("roxavendelso", "Avenida del Solano")
    AddTextEntry("roxencantdr", "Encanto Drive")
    AddTextEntry("roxsierludr", "Sierra Lucía Drive")
    AddTextEntry("roxcamidecie", "Camino de Cielo")
    AddTextEntry("roxladlan", "Ladera Lane")
    AddTextEntry("roxcypholl", "Cypress Hollow Lane")
    AddTextEntry("roxmarineaven", "Marinera Avenue")

     --[[ Zones ]]--   
    AddTextEntry("roxwood", "Roxwood")
    AddTextEntry("roxcoun", "Roxwood County")
    AddTextEntry("roxcity", "Roxwood City")
    AddTextEntry("roxpark", "Roxwood State Park")
    AddTextEntry("roxcfar", "Chulz Family Farm")
    AddTextEntry("roxmarb", "Marina Beach")
    AddTextEntry("roxdock", "Marina Docks")
    AddTextEntry("roxwatp", "Poisedon's Thrills Water Park")
    AddTextEntry("roxrocp", "Paleto Rock Natural Preserve")
    AddTextEntry("roxpwra", "Roxwood Power Plant")
    AddTextEntry("rxfrmwn", "Willy's Nuts Farm")
    AddTextEntry("roxairp", "Arroyo Muerto Municipal Airport")
    AddTextEntry("roxcont", "Piger Logistics Inland Container Terminal")
    AddTextEntry("roxjuni", "Juniper by the Shore")
    AddTextEntry("roxlomb", "Lombardt Bay")
    AddTextEntry("roxlagc", "Arroyo Muerto International Raceway")
    AddTextEntry("roxahou", "Arroyo Muerto Housing Park")
end)
